# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92045a9a6032f61f79cb947364eefe7bc43c4e996293f885536e8be1d3646ce203520a53338211208a370326eca11cccf31f41092b23a1536f0d9c19bc2cd861

test:
  secret_key_base: f89417fcfd038f308dad667a3b1e27bff507f99c2fd3f646ac94c7a48d639d73c769859824a8c25b0d343008e9c0be62967935da08efd725175585f7296a5d90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
